// SemanticEmbedder.swift
// STT
//
// Stage 3 embedding: BERT-style WordPiece tokeniser + CoreML MiniLM-L6-v2.
// Mirrors SemanticFallback._tokenise() / _embed_onnx() in
// IntentClassifier/scripts/nlu/semantic.py exactly — same max_len=64,
// same mean-pool over attention mask, same L2 normalisation.
//
// Bundle requirements (both must be present for Stage 3 to activate):
//   MiniLMEmbedder.mlpackage  — generated by: python scripts/export_coreml.py
//   minilm-vocab.txt          — copy from IntentClassifier/models/minilm-vocab.txt
//
// If either file is missing, init() returns nil and the caller skips Stage 3.
// This is intentional: the app ships and functions at full TF-IDF + keyword
// accuracy; semantic rescue activates only when the CoreML model is bundled.

import CoreML
import Foundation

/// Embeds text into a 384-dimensional L2-normalised Float vector
/// using MiniLM-L6-v2 via CoreML (Apple Neural Engine on A12+).
// Immutable after init (model + vocab are `let`), so safe to hand across the
// background load Task in IntentClassifierService.
final class SemanticEmbedder: @unchecked Sendable {

    private let model: MLModel
    private let vocab: [String: Int]

    // Must match the fixed sequence length the CoreML model was exported with.
    // The model description declares shape (1 x 32) for all three inputs;
    // sending a shorter sequence without padding causes a shape-mismatch crash.
    private static let maxLen = 32

    deinit {
        print("[Deinit] SemanticEmbedder (MLModel + vocab released)")
    }

    // MARK: - Init

    init?() {
        let miniLMURL = Bundle.module.url(forResource: "MiniLMEmbedder", withExtension: "mlmodelc")
                     ?? Bundle.module.url(forResource: "MiniLMEmbedder", withExtension: "mlpackage")
        guard
            let modelURL = miniLMURL,
            let vocabURL = Bundle.module.url(forResource: "minilm-vocab",
                                           withExtension: "txt"),
            let vocabText = try? String(contentsOf: vocabURL, encoding: .utf8)
        else { return nil }

        let config = MLModelConfiguration()
        config.computeUnits = .all       // prefers ANE on A12+, GPU fallback on older
        guard let m = try? MLModel(contentsOf: modelURL, configuration: config) else { return nil }
        model = m

        var v = [String: Int]()
        v.reserveCapacity(30_722)        // standard BERT vocab size
        for (i, line) in vocabText.components(separatedBy: "\n").enumerated() {
            let tok = line.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !tok.isEmpty else { continue }
            v[tok] = i
        }
        vocab = v
    }

    // MARK: - Public API

    /// Produces a 384-element L2-normalised embedding, or nil on any failure.
    /// Async so CoreML scheduling doesn't block the calling actor.
    func embed(_ text: String) async -> [Float]? {
        let (inputIDs, mask, tokenTypeIDs) = tokenize(text.lowercased())
        let n = inputIDs.count

        guard n > 0,
              let idsArray  = try? MLMultiArray(shape: [1, n as NSNumber], dataType: .int32),
              let maskArray = try? MLMultiArray(shape: [1, n as NSNumber], dataType: .int32),
              let typeArray = try? MLMultiArray(shape: [1, n as NSNumber], dataType: .int32)
        else { return nil }

        // Write straight into the backing buffers — the arrays are freshly
        // allocated and contiguous, so element stride is 1. Avoids ~3n NSNumber
        // boxing allocations per call.
        let idsPtr  = idsArray.dataPointer.assumingMemoryBound(to: Int32.self)
        let maskPtr = maskArray.dataPointer.assumingMemoryBound(to: Int32.self)
        let typePtr = typeArray.dataPointer.assumingMemoryBound(to: Int32.self)
        for i in 0..<n {
            idsPtr[i]  = inputIDs[i]
            maskPtr[i] = mask[i]
            typePtr[i] = tokenTypeIDs[i]
        }

        guard let featureProvider = try? MLDictionaryFeatureProvider(dictionary: [
            "input_ids":      MLFeatureValue(multiArray: idsArray),
            "attention_mask": MLFeatureValue(multiArray: maskArray),
            "token_type_ids": MLFeatureValue(multiArray: typeArray),
        ]) else { return nil }

        guard let output = try? await model.prediction(from: featureProvider) else { return nil }

        // CoreML output name matches the ONNX graph: "last_hidden_state" shape [1, seqLen, 384]
        guard let hidden = output.featureValue(for: "last_hidden_state")?.multiArrayValue
        else { return nil }

        return meanPoolAndNormalize(hidden, seqLen: n, mask: mask)
    }

    // MARK: - Tokenisation (mirrors semantic.py _tokenise)

    private func tokenize(_ text: String) -> (ids: [Int32], mask: [Int32], types: [Int32]) {
        let pad = Int32(vocab["[PAD]"] ?? 0)
        let unk = Int32(vocab["[UNK]"] ?? 100)
        let cls = Int32(vocab["[CLS]"] ?? 101)
        let sep = Int32(vocab["[SEP]"] ?? 102)

        var ids: [Int32] = [cls]
        let pieces = wordpiece(text)
        for p in pieces.prefix(Self.maxLen - 2) {
            ids.append(Int32(vocab[p] ?? Int(unk)))
        }
        ids.append(sep)

        // Mask: 1 for real tokens, 0 for padding. The model's fixed shape requires
        // all three arrays to be exactly maxLen regardless of actual text length.
        var mask  = [Int32](repeating: 1, count: ids.count)
        var types = [Int32](repeating: 0, count: ids.count)

        let padCount = Self.maxLen - ids.count
        if padCount > 0 {
            ids   += [Int32](repeating: pad, count: padCount)
            mask  += [Int32](repeating: 0,   count: padCount)
            types += [Int32](repeating: 0,   count: padCount)
        }

        return (ids, mask, types)
    }

    // MARK: - WordPiece (mirrors semantic.py _wordpiece exactly)

    private func wordpiece(_ text: String) -> [String] {
        // re.findall(r"\w+|[^\w\s]", text) — words then isolated punctuation
        let pattern = try! NSRegularExpression(pattern: #"\w+|[^\w\s]"#)
        let range   = NSRange(text.startIndex..., in: text)
        let words   = pattern.matches(in: text, range: range).map {
            String(text[Range($0.range, in: text)!])
        }

        var result = [String]()
        for word in words {
            let chars = Array(word)
            if chars.count > 100 { result.append("[UNK]"); continue }

            var subTokens = [String]()
            var start     = 0
            var isBad     = false

            while start < chars.count {
                var found: String?
                var end = chars.count
                while start < end {
                    var substr = String(chars[start..<end])
                    if start > 0 { substr = "##" + substr }
                    if vocab[substr] != nil { found = substr; break }
                    end -= 1
                }
                if let f = found {
                    subTokens.append(f)
                    start = end
                } else {
                    isBad = true; break
                }
            }
            result.append(contentsOf: isBad ? ["[UNK]"] : subTokens)
        }
        return result
    }

    // MARK: - Mean pool + L2 normalise (mirrors _embed_onnx)

    private func meanPoolAndNormalize(_ hidden: MLMultiArray,
                                      seqLen: Int,
                                      mask: [Int32]) -> [Float] {
        let dim = 384
        var pooled      = [Float](repeating: 0, count: dim)
        var totalWeight: Float = 0

        // The output is [1, seq, dim]. Read it through the raw backing buffer using
        // the model's declared strides instead of MLMultiArray subscripting, which
        // boxes every element into an NSNumber (~seq*dim allocations per call).
        let strides   = hidden.strides.map { $0.intValue }
        let rowStride = strides.count >= 3 ? strides[1] : dim
        let colStride = strides.count >= 3 ? strides[2] : 1

        func pool<T: BinaryFloatingPoint>(_ base: UnsafeMutablePointer<T>) {
            for pos in 0..<seqLen {
                let w = Float(mask[pos])
                guard w != 0 else { continue }
                totalWeight += w
                let row = pos * rowStride
                for d in 0..<dim {
                    pooled[d] += Float(base[row + d * colStride]) * w
                }
            }
        }

        func poolBySubscript() {
            for pos in 0..<seqLen {
                let w = Float(mask[pos])
                guard w != 0 else { continue }
                totalWeight += w
                for d in 0..<dim {
                    pooled[d] += hidden[[0, NSNumber(value: pos), NSNumber(value: d)]].floatValue * w
                }
            }
        }

        // NOTE: MLMultiArrayDataType.float16 is an iOS 16+ symbol, so it must be
        // referenced only inside an availability guard (not a bare switch case).
        // Pre-iOS16, CoreML hands back FP16 outputs as .float32 anyway.
        let dt = hidden.dataType
        if dt == .float32 {
            pool(hidden.dataPointer.assumingMemoryBound(to: Float.self))
        } else if dt == .double {
            pool(hidden.dataPointer.assumingMemoryBound(to: Double.self))
        } else if #available(iOS 16.0, *), dt == .float16 {
            pool(hidden.dataPointer.assumingMemoryBound(to: Float16.self))
        } else {
            poolBySubscript()
        }

        if totalWeight > 0 { for d in 0..<dim { pooled[d] /= totalWeight } }

        // L2 normalise — mandatory; the head was trained on normalised embeddings
        let norm = sqrt(pooled.reduce(0) { $0 + $1 * $1 })
        if norm > 0 { for d in 0..<dim { pooled[d] /= norm } }
        return pooled
    }
}
