// IntentClassifierCoreMLParityTests.swift
// STTTests
//
// Cross-language parity for the temperature-scaled CoreML intent classifiers.
//
// Validates the iOS device path — Swift TF-IDF  →  .mlpackage `logits`  →
// softmax(logits / T) — against golden fixtures generated by the Python/NumPy
// reference in the IntentClassifier repo
// (multilingual/test/test_coreml_multilingual.py --emit-fixtures). The fixtures
// (coreml_golden_fixtures.json) are the single source of truth both languages
// compare to.
//
// PLATFORM REALITY: this test does `import CoreML` and loads `.mlpackage`
// resources, so it runs on **macOS + Xcode only** (a macOS CI job or a dev Mac).
// It CANNOT run on a Linux routine. The pure-Swift TF-IDF + linear math is also
// exercised here, but the logits come from the real Core ML model, so the whole
// test is gated on the model resources being bundled into the test target.
//
// To run on macOS, add per-model resources to the STTTests target:
//   IntentClassifier_<model>.mlpackage           (from the exporter)
//   <model>_intent_classifier_weights.json       (vocab + idf + temperature)
// for any of: en, fr, de, da, multilingual, multilingual_small. Models whose
// resources are absent are skipped (not failed), so the test is safe to land
// before all six packages are wired into the Xcode project.

import XCTest
import CoreML
@testable import VoiceIntentKit

final class IntentClassifierCoreMLParityTests: XCTestCase {

    // FP16 tolerance: the CoreML matmul is float16, so confidences track the
    // fp32 Python reference to ~1e-2. The 0.70 gate must agree exactly.
    private let confTolerance = 1e-2
    private let gateThreshold = 0.70

    // MARK: - Fixture model

    private struct Fixture: Decodable {
        let utterance: String
        let model: String
        let temperature: Double
        let expected_intent: String
        let expected_top1_confidence: Double
        let expected_logits: [Double]
    }

    // MARK: - Minimal device scorer (mirrors IntentClassifierService)

    /// Loads vocab/idf/labels/temperature + the CoreML model for one language and
    /// reproduces the on-device scoring path. Returns nil if either resource is
    /// missing from the test bundle (→ the test skips that model).
    private struct ModelScorer {
        let labels: [String]
        let vocab: [String: Int]
        let idf: [Double]
        let temperature: Double
        let model: MLModel

        init?(_ name: String) {
            let bundle = Bundle(for: IntentClassifierCoreMLParityTests.self)
            guard
                let weightsURL = bundle.url(forResource: "\(name)_intent_classifier_weights",
                                            withExtension: "json"),
                let data = try? Data(contentsOf: weightsURL),
                let obj  = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                let labels = obj["labels"] as? [String],
                let vocab  = obj["vocab"]  as? [String: Int],
                let idf    = obj["idf"]    as? [Double]
            else { return nil }

            let modelURL = bundle.url(forResource: "IntentClassifier_\(name)", withExtension: "mlmodelc")
                        ?? bundle.url(forResource: "IntentClassifier_\(name)", withExtension: "mlpackage")
            guard let url = modelURL else { return nil }
            let config = MLModelConfiguration()
            config.computeUnits = .all
            guard let m = try? MLModel(contentsOf: url, configuration: config) else { return nil }

            self.labels = labels
            self.vocab = vocab
            self.idf = idf
            self.temperature = (obj["temperature"] as? Double) ?? 1.0
            self.model = m
        }

        /// lowercase → split on non-alphanumerics → unigrams + adjacent bigrams.
        private func tokenize(_ text: String) -> [String] {
            let words = text.lowercased()
                .components(separatedBy: CharacterSet.alphanumerics.inverted)
                .filter { !$0.isEmpty }
            var tokens = words
            for i in words.indices.dropLast() { tokens.append(words[i] + " " + words[i + 1]) }
            return tokens
        }

        /// Sublinear TF-IDF over the pruned vocab, then L2-normalise.
        private func tfidfVector(_ text: String) -> [Double] {
            var counts: [Int: Int] = [:]
            for tok in tokenize(text) { if let i = vocab[tok] { counts[i, default: 0] += 1 } }
            var vec = [Double](repeating: 0, count: idf.count)
            for (i, c) in counts { vec[i] = (1.0 + log(Double(c))) * idf[i] }
            let norm = sqrt(vec.reduce(0) { $0 + $1 * $1 })
            guard norm > 0 else { return vec }
            return vec.map { $0 / norm }
        }

        /// Real Core ML `logits` output for `text`, aligned with `labels`.
        func logits(_ text: String) throws -> [Double] {
            let vec = tfidfVector(text)
            // Build with the rank the model declares for tfidf_vector — the English
            // export takes [N], the multilingual mlprogram export takes [1, N].
            // Mirrors TFIDFLogisticScorer.inputShape(for:vectorLength:).
            let shape = TFIDFLogisticScorer.inputShape(for: model, vectorLength: vec.count)
            let arr = try MLMultiArray(shape: shape, dataType: .float32)
            let p = arr.dataPointer.assumingMemoryBound(to: Float.self)
            for i in 0..<vec.count { p[i] = Float(vec[i]) }
            let input = try MLDictionaryFeatureProvider(dictionary: [
                "tfidf_vector": MLFeatureValue(multiArray: arr)
            ])
            let out = try model.prediction(from: input)
            guard let logits = out.featureValue(for: "logits")?.multiArrayValue,
                  logits.count == labels.count
            else { throw XCTSkip("model '\(model)' has no 'logits' output of length \(labels.count)") }
            return (0..<logits.count).map { logits[$0].doubleValue }
        }

        func softmaxScaled(_ logits: [Double]) -> [Double] {
            let t = temperature > 0 ? temperature : 1.0
            let scaled = logits.map { $0 / t }
            let mx = scaled.max() ?? 0
            let exps = scaled.map { exp($0 - mx) }
            let sum = exps.reduce(0, +)
            return sum == 0 ? scaled.map { _ in 1.0 / Double(scaled.count) } : exps.map { $0 / sum }
        }
    }

    // MARK: - Tests

    private func loadFixtures() throws -> [Fixture] {
        let bundle = Bundle(for: type(of: self))
        guard let url = bundle.url(forResource: "coreml_golden_fixtures", withExtension: "json") else {
            throw XCTSkip("coreml_golden_fixtures.json not in test bundle — add it to STTTests resources.")
        }
        return try JSONDecoder().decode([Fixture].self, from: Data(contentsOf: url))
    }

    /// Per model: Swift device path must match the Python golden fixtures on
    /// intent, top-1 confidence (within FP16 tolerance) and the 0.70 gate.
    func testDeviceParityAgainstGoldenFixtures() throws {
        let fixtures = try loadFixtures()
        XCTAssertFalse(fixtures.isEmpty, "no fixtures decoded")

        let byModel = Dictionary(grouping: fixtures, by: { $0.model })
        var ranAnyModel = false

        for (modelName, items) in byModel.sorted(by: { $0.key < $1.key }) {
            guard let scorer = ModelScorer(modelName) else {
                // Resources for this model aren't bundled — skip, don't fail.
                print("⏭  skipping '\(modelName)': IntentClassifier_\(modelName).mlpackage / "
                      + "\(modelName)_intent_classifier_weights.json not in test bundle")
                continue
            }
            ranAnyModel = true

            var intentMismatch = 0, gateDisagree = 0, maxConfDelta = 0.0
            for f in items {
                let logits = try scorer.logits(f.utterance)
                let probs = scorer.softmaxScaled(logits)
                let top = probs.indices.max(by: { probs[$0] < probs[$1] }) ?? 0
                let intent = scorer.labels[top]
                let conf = probs[top]

                if intent != f.expected_intent { intentMismatch += 1 }
                maxConfDelta = max(maxConfDelta, abs(conf - f.expected_top1_confidence))

                let deviceFires = conf >= gateThreshold
                let pythonFires = f.expected_top1_confidence >= gateThreshold
                if deviceFires != pythonFires { gateDisagree += 1 }
            }

            print("✅ \(modelName): n=\(items.count)  intentMismatch=\(intentMismatch)  "
                  + "gateDisagree=\(gateDisagree)  maxConfΔ=\(maxConfDelta)")
            XCTAssertEqual(intentMismatch, 0, "[\(modelName)] intent mismatches vs Python")
            XCTAssertEqual(gateDisagree, 0, "[\(modelName)] 0.70-gate disagreements vs Python")
            XCTAssertLessThanOrEqual(maxConfDelta, confTolerance,
                                     "[\(modelName)] top-1 confidence exceeds FP16 tolerance")
        }

        try XCTSkipUnless(ranAnyModel,
            "No model resources bundled — add IntentClassifier_<model>.mlpackage + "
            + "<model>_intent_classifier_weights.json to STTTests to exercise this test on macOS.")
    }

    /// Sanity: temperature scaling is rank-preserving — the softmax(logits/T)
    /// argmax equals the raw-logit argmax for every fixture. This part needs no
    /// CoreML model (it uses the fixtures' own logits), so it runs anywhere the
    /// test bundle loads.
    func testTemperatureIsRankPreserving() throws {
        let fixtures = try loadFixtures()
        for f in fixtures {
            let rawTop = f.expected_logits.indices.max { f.expected_logits[$0] < f.expected_logits[$1] }!
            let t = f.temperature > 0 ? f.temperature : 1.0
            let scaled = f.expected_logits.map { $0 / t }
            let scaledTop = scaled.indices.max { scaled[$0] < scaled[$1] }!
            XCTAssertEqual(rawTop, scaledTop,
                "temperature re-ranked '\(f.utterance)' (\(f.model)) — must be rank-preserving")
        }
    }
}
