// TopicDerivationParityTests.swift
// VoiceIntentKitTests
//
// Topic derivation, against the Python reference that produced the training
// data. This is the test that did not exist when `strippingDateTime` was first
// written, and 8 of 20 utterances diverged without anything failing.
//
// Fixtures are GENERATED by running `entities.py::strip_datetime` and
// `engine.py::_derive_topic` — never hand-written. A hand-written expectation
// records what someone believed the reference does; the point of this file is
// that belief was wrong in eight places.

import XCTest
@testable import VoiceIntentKit

final class TopicDerivationParityTests: XCTestCase {

    private struct Expectations: Decodable {
        struct Case: Decodable {
            let text: String
            /// nil means the reference derived no topic at all.
            let expected: String?
        }
        let stripDatetime: [Case]
        let deriveTopic: [Case]

        enum CodingKeys: String, CodingKey {
            case stripDatetime = "strip_datetime"
            case deriveTopic = "derive_topic"
        }
    }

    private var pack: ResolvedPack!
    private var expectations: Expectations!

    override func setUpWithError() throws {
        try super.setUpWithError()
        pack = try PackTestSupport.loadPack()
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/topic_expectations.json")
        expectations = try JSONDecoder().decode(Expectations.self, from: Data(contentsOf: url))
    }

    /// `PackDateTimeParser.strippingDateTime` against
    /// `EntityExtractor.strip_datetime`.
    ///
    /// The reference has two implementations and English uses
    /// `_en_strip_patterns`, not `_strip_datetime_lex`. They differ in pattern
    /// SET and pattern ORDER, and mirroring the wrong one is what produced
    /// "dinner 7" for "dinner at 7" and "buy milk the" for "buy milk in the
    /// morning".
    func testStripDateTimeMatchesTheReference() throws {
        let parser = PackDateTimeParser(grammar: pack.lexicon.datetime)
        var failures: [String] = []

        for testCase in expectations.stripDatetime {
            let actual = parser.strippingDateTime(testCase.text)
            let expected = testCase.expected ?? ""
            if actual != expected {
                failures.append("\(testCase.text.debugDescription): expected "
                                + "\(expected.debugDescription), got \(actual.debugDescription)")
            }
        }

        XCTAssertTrue(failures.isEmpty, """
            \(failures.count)/\(expectations.stripDatetime.count) divergence(s) from the reference:
            \(failures.joined(separator: "\n"))
            """)
    }

    /// The full three-step derivation — carriers, then date/time, then the
    /// leading connector — through the live engine.
    ///
    /// Step three was absent from Swift entirely, so a stripped time left its
    /// connective behind: "remind me at 9pm for dinner" named the reminder
    /// "for dinner".
    func testDeriveTopicMatchesTheReference() async throws {
        var failures: [String] = []

        for testCase in expectations.deriveTopic {
            let engine = makeEngine()
            let response = await engine.handle(testCase.text)
            let actual = filledName(from: response)

            if actual != testCase.expected {
                failures.append("""
                    \(testCase.text.debugDescription): expected \
                    \(String(describing: testCase.expected)), got \(String(describing: actual))
                    """)
            }
        }

        XCTAssertTrue(failures.isEmpty, """
            \(failures.count)/\(expectations.deriveTopic.count) divergence(s) from the reference:
            \(failures.joined(separator: "\n"))
            """)
    }

    /// The connector must also go when it is the whole remainder, or the topic
    /// is the connector itself. The reference had this bug too; it is fixed on
    /// both sides rather than reproduced.
    func testConnectorThatIsTheEntireRemainderIsRemoved() async throws {
        let engine = makeEngine()
        let response = await engine.handle("set a reminder for 5pm")
        XCTAssertNil(filledName(from: response),
                     "\"for\" is not a reminder name — the slot should still be unfilled")
    }

    // MARK: - Helpers

    /// Wired as `PackEngineFactory` wires it, with the pack's own carriers and
    /// connectors, and a classifier stubbed to be confident so no confirmation
    /// intervenes.
    private func makeEngine() -> NLUEngine {
        NLUEngine(
            schema: PackEngineFactory.schema(from: pack),
            classifier: TopicStubClassifier(),
            entities: PackSlotResolver(pack: pack),
            uncertain: [],
            noIdioms: [],
            carriers: pack.lexicon.carriers,
            leadingConnectors: pack.lexicon.leadingConnectors,
            confirmationGates: PackEngineFactory.confirmationGates(from: pack))
    }

    private func filledName(from response: NLUResponse) -> String? {
        switch response {
        case .prompt(_, _, let filled):
            return filled["name"]
        case .fulfill(_, _, let parameters, _, _, _, _):
            return parameters["name"]
        default:
            return nil
        }
    }
}

/// Always `reminders.task.create` at a confidence above the pack's confirmation
/// band, so every case exercises the topic path rather than the gate.
private actor TopicStubClassifier: IntentClassifying {

    func classifyAsync(_ text: String) async -> ClassificationResult {
        ClassificationResult(label: "reminders.task.create",
                             confidence: 0.97,
                             semanticRescue: false,
                             breakdown: ClassificationBreakdown(winningStage: 2,
                                                                stage2: nil,
                                                                stage3: nil))
    }

    func genaiURL(for text: String) -> URL { URL(string: "https://example.invalid/q")! }
    func warmUp() async {}
    func loadStage3() async {}
    func releaseStage3() async {}
}
