// IntentClassifierService.swift
// STT
//
// 3-stage on-device intent classification pipeline.
// Mirrors the architecture in IntentClassifier/scripts/nlu/classifier.py
// and IntentClassifier/scripts/nlu/semantic.py.
//
// Stage 1 — Keyword rules   (KeywordMatcher)         sync, ~0 ms
// Stage 2 — TF-IDF + LogReg (CoreML intent model)    async, ~2 ms
// Stage 3 — Semantic rescue (MiniLM-L6-v2 via CoreML) async, ~8 ms
//
// Stage 2 primary: IntentClassifier.mlpackage (generated by export_coreml.py).
// Stage 2 fallback: intent_classifier_weights.json (pure-Swift reimplementation,
//   used automatically if the .mlpackage is absent from the bundle).
//
// Stage 3 activates only when Stage 2 returns low confidence or "Default Fallback
// Intent". Both SemanticEmbedder and SemanticClassifier return nil from their
// inits if their bundle artifacts are missing — Stage 3 is skipped silently.

import CoreML
import Foundation
import os.log

// MARK: - Result type

public struct ClassificationResult: Sendable {
    public let label: String
    public let confidence: Double
    /// True when Stage 3 (MiniLM semantic rescue) produced this result.
    public let semanticRescue: Bool
    /// Per-stage detail for the eye-button debug panel.
    public let breakdown: ClassificationBreakdown
}

// MARK: - Service

// `actor` so its methods run on a serial executor off the main thread: callers
// reach it with `await classifier.classifyAsync(...)`, which hops off main for
// the call and back on return. This replaces the previous `@unchecked Sendable`
// class + per-call `Task.detached` hop — the actor provides both off-main
// execution and serialisation for free.
public actor IntentClassifierService {

    // MARK: - Lifecycle (instance-based, no singleton)
    //
    // The singleton was removed so we can test whether dropping the last strong
    // reference actually deinits the service (and downstream MiniLM state).
    // Owners pass an instance around explicitly.

    deinit {
        print("[Deinit] IntentClassifierService")
    }

    // MARK: - Stage 1

    private let keywordMatcher = KeywordMatcher()

    // MARK: - Stage 2 — CoreML (primary)

    private let coreMLModel: MLModel?

    // MARK: - Stage 2 — JSON weights fallback

    // vocab + idf are loaded at init — they're needed to vectorize text for the CoreML
    // model's tfidf_vector input, so they can't be deferred.
    private let labels: [String]
    private let vocab: [String: Int]
    private let idf: [Double]

    /// LogReg coefficient matrix and intercepts — only needed when CoreML prediction
    /// itself fails. Deferred so the ~5-25 MB coef array is never allocated when
    /// CoreML is healthy. Struct is value-type so it can be nilled to reclaim memory.
    private struct LogRegWeights {
        let coef: [[Double]]
        let intercept: [Double]
    }

    /// Nil until the first CoreML prediction failure triggers the pure-Swift fallback.
    private var logRegWeights: LogRegWeights?
    /// Stored so the lazy loader can open the file without hitting Bundle.main again.
    private let weightsURL: URL?

    /// Per-class isotonic calibration (device logit → server-calibrated prob),
    /// exported by export_ios_weights.py. `nil` for older bundles, in which case
    /// Stage 2 falls back to plain softmax. See `calibratedProbs(from:)`.
    private let calibrationMaps: [(x: [Double], y: [Double])]?

    // MARK: - Stage 3

    // Both nil until `loadStage3()` is called (manual lifecycle for memory
    // experiment). When loaded, MiniLM weights + ANE specialization live here.
    private var semanticEmbedder: SemanticEmbedder?
    private var semanticClassifier: SemanticClassifier?

    // MARK: - Thresholds

    private let confThreshold: Double
    private let confGapThreshold: Double
    private let genaiBaseURL: String
    private static let semanticThreshold: Double = 0.55

    private static let fallbackLabel = "Default Fallback Intent"

    private let logger = Logger(subsystem: "com.stt.module", category: "IntentClassifier")

    // MARK: - Init

    public init() {
        // -- Stage 2 primary: CoreML --
        // Xcode compiles .mlpackage → .mlmodelc at build time; try compiled form first.
        let intentURL = Bundle.main.url(forResource: "IntentClassifier", withExtension: "mlmodelc")
                     ?? Bundle.main.url(forResource: "IntentClassifier", withExtension: "mlpackage")
        if let modelURL = intentURL {
            let config = MLModelConfiguration()
            config.computeUnits = .all
            coreMLModel = try? MLModel(contentsOf: modelURL, configuration: config)
        } else {
            coreMLModel = nil
        }

        // -- Stage 2 fallback: JSON weights --
        // vocab + idf are needed on every classification (they build the tfidf_vector
        // input the CoreML model consumes), so they load eagerly here. The LogReg
        // coef matrix + intercepts (~5-25 MB) are NOT retained — they're re-loaded
        // lazily by ensureLogRegWeights() only if a CoreML prediction fails, so they
        // never sit in idle memory when CoreML is healthy.
        // NOTE: JSONSerialization below still parses the whole file (incl. coef) into a
        // transient dictionary at launch; that peak is unchanged. Only the *retained*
        // footprint shrinks. Splitting coef into its own file would remove the peak too.
        let jsonURL = Bundle.main.url(forResource: "intent_classifier_weights",
                                      withExtension: "json")
        guard
            let url  = jsonURL,
            let data = try? Data(contentsOf: url),
            let obj  = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else {
            fatalError("IntentClassifierService: intent_classifier_weights.json not found in bundle.")
        }
        weightsURL       = jsonURL
        labels           = obj["labels"]            as! [String]
        vocab            = obj["vocab"]              as! [String: Int]
        idf              = obj["idf"]                as! [Double]
        confThreshold    = obj["conf_threshold"]     as? Double ?? 0.70
        confGapThreshold = obj["conf_gap_threshold"] as? Double ?? 0.20
        genaiBaseURL     = obj["genai_base_url"]     as? String ?? ""

        // Calibration maps are small (~KB) and used on every CoreML classification
        // to rescale raw logits → calibrated probabilities — load them now.
        if let cal  = obj["calibration"] as? [String: Any],
           let rows = cal["maps"] as? [[String: Any]],
           rows.count == labels.count {
            let parsed: [(x: [Double], y: [Double])] = rows.map {
                (($0["x"] as? [Double]) ?? [], ($0["y"] as? [Double]) ?? [])
            }
            calibrationMaps = parsed.allSatisfy { !$0.x.isEmpty && $0.x.count == $0.y.count }
                ? parsed : nil
        } else {
            calibrationMaps = nil
        }

        // Stage 3 deliberately not loaded at init — call `loadStage3()` to
        // bring it up on demand. `semanticEmbedder` and `semanticClassifier`
        // stay nil until then; Stage 3 calls in `classifyAsync` are skipped.

        let stage2 = coreMLModel != nil ? "CoreML" : "JSON weights"
        Logger(subsystem: "com.stt.module", category: "IntentClassifier")
            .info("IntentClassifier ready — Stage2: \(stage2), Stage3 semantic: loading in background")
    }

    // MARK: - Public API

    /// Pre-loads and pre-compiles the CoreML graphs (including Apple Neural Engine
    /// specialization, which happens on the first prediction) on a background task,
    /// so the first real classification has no cold-start latency. Safe to call
    /// repeatedly; the heavy load runs once via the embedder Task.
    public func warmUp() async {
        if let embedder = semanticEmbedder {
            _ = await embedder.embed("hello")
        }
        if let model = coreMLModel {
            _ = coreMLProbabilities("hello", model: model)
        }
    }

    /// Manually load Stage 3 (MiniLM embedder + semantic head) and trigger its
    /// ANE specialization. Idempotent — no-op if already loaded.
    public func loadStage3() async {
        if semanticEmbedder == nil {
            // Off the actor's executor: MiniLM init reads a 16 MB model file
            // and a 228 KB vocab.
            let task = Task.detached(priority: .userInitiated) { SemanticEmbedder() }
            semanticEmbedder = await task.value
        }
        if semanticClassifier == nil {
            semanticClassifier = SemanticClassifier()
        }
        // Trigger ANE compile / weight load — without this, the heavy memory
        // hit doesn't materialize until the first real `embed()` call.
        if let embedder = semanticEmbedder {
            _ = await embedder.embed("hello")
        }
    }

    /// Manually release Stage 3 refs. Pair with `MemoryProbe` to verify whether
    /// CoreML actually frees the ANE-resident weights when our handles drop.
    public func releaseStage3() {
        semanticEmbedder = nil
        semanticClassifier = nil
    }

    /// Full 3-stage async classification. Use this from NLUEngine.
    /// Returns `semanticRescue: true` when Stage 3 saved a low-confidence Stage 2 result.
    public func classifyAsync(_ text: String) async -> ClassificationResult {
        // Stage 1
        if let kw = keywordMatcher.match(text) {
            let bd = ClassificationBreakdown(winningStage: 1, stage2: nil, stage3: nil)
            return ClassificationResult(label: kw.label, confidence: kw.confidence,
                                        semanticRescue: false, breakdown: bd)
        }

        // Stage 2 — already off the main thread: this method runs on the actor's
        // own executor, so no extra detached hop is needed.
        let (stage2Label, stage2Conf) = stage2Classify(text)
        let s2 = ClassificationBreakdown.StageResult(stage: 2, intent: stage2Label, confidence: stage2Conf)
        let stage2Failed = stage2Label == Self.fallbackLabel || stage2Conf < confThreshold

        if !stage2Failed {
            let bd = ClassificationBreakdown(winningStage: 2, stage2: s2, stage3: nil)
            return ClassificationResult(label: stage2Label, confidence: stage2Conf,
                                        semanticRescue: false, breakdown: bd)
        }

        // Stage 3 — only runs when Stage 2 is uncertain AND Stage 3 has been
        // explicitly loaded via `loadStage3()`.
        if let embedder = semanticEmbedder, let head = semanticClassifier,
           let embedding = await embedder.embed(text) {
            let (semLabel, semConf) = head.classify(embedding)
            let s3 = ClassificationBreakdown.StageResult(stage: 3, intent: semLabel, confidence: semConf)
            if semLabel != Self.fallbackLabel && semConf >= Self.semanticThreshold {
                logger.info("Semantic rescue: '\(text)' → \(semLabel) (\(String(format: "%.2f", semConf)))")
                let bd = ClassificationBreakdown(winningStage: 3, stage2: s2, stage3: s3)
                return ClassificationResult(label: semLabel, confidence: semConf,
                                            semanticRescue: true, breakdown: bd)
            }
            // Stage 3 ran but neither stage met threshold → GENAI fallback.
            let bd = ClassificationBreakdown(winningStage: nil, stage2: s2, stage3: s3)
            return ClassificationResult(label: stage2Label, confidence: stage2Conf,
                                        semanticRescue: false, breakdown: bd)
        }

        // Stage 3 not loaded → GENAI fallback, only Stage 2 data available.
        let bd = ClassificationBreakdown(winningStage: nil, stage2: s2, stage3: nil)
        return ClassificationResult(label: stage2Label, confidence: stage2Conf,
                                    semanticRescue: false, breakdown: bd)
    }

    /// Sync Stages 1+2 only. Used by `predict()` and legacy callers.
    public func classify(_ text: String) -> (label: String, confidence: Double) {
        if let kw = keywordMatcher.match(text) { return (kw.label, kw.confidence) }
        return stage2Classify(text)
    }

    /// Classify and apply confidence/gap thresholds, returning an `IntentResult`.
    /// Prefer `classifyAsync` from async contexts for full semantic rescue.
    public func predict(_ text: String) -> IntentResult {
        if let kw = keywordMatcher.match(text) {
            return .intent(label: kw.label, confidence: kw.confidence)
        }
        let (probs, top) = stage2Scores(text)
        guard !probs.isEmpty else { return .genai(url: genaiURL(for: text), confidence: 0.0) }
        let conf = probs[top]
        if conf >= confThreshold {
            // Gap to the strongest competing class (the predicted label is the
            // base-model argmax, which may not be the calibrated argmax).
            let runnerUp = probs.indices.filter { $0 != top }.map { probs[$0] }.max() ?? 0.0
            if conf - runnerUp >= confGapThreshold {
                return .intent(label: labels[top], confidence: conf)
            }
        }
        return .genai(url: genaiURL(for: text), confidence: conf)
    }

    /// GenAI fallback URL for an unrecognised query.
    public func genaiURL(for text: String) -> URL {
        let encoded = text.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? text
        return URL(string: genaiBaseURL + encoded) ?? URL(string: "https://genai.yourcompany.com")!
    }

    // MARK: - Stage 2 implementation

    /// Returns the top intent and its (calibrated, when available) confidence.
    private func stage2Classify(_ text: String) -> (label: String, confidence: Double) {
        let (probs, top) = stage2Scores(text)
        guard !probs.isEmpty else { return (Self.fallbackLabel, 0.0) }
        return (labels[top], probs[top])
    }

    /// Per-class Stage-2 probabilities (aligned with `labels`) plus the index of
    /// the predicted intent.
    ///
    /// The predicted intent is always the base model's argmax (the softmax/logit
    /// winner). When isotonic calibration tables are present we additionally
    /// recalibrate the probabilities so the device's *confidence* matches the
    /// server's CalibratedClassifierCV — without this, correct mid-confidence
    /// intents fall below the 0.70 threshold. Crucially we DON'T let calibration
    /// re-rank: each class has its own isotonic map, and the catch-all "Default
    /// Fallback Intent" can otherwise steal probability mass after normalisation
    /// and flip a confident command to a fallback. Keeping the label on the base
    /// argmax preserves the model's decision while fixing only the confidence.
    private func stage2Scores(_ text: String) -> (probs: [Double], top: Int) {
        if let maps = calibrationMaps {
            let logits = logitsForScoring(text)
            // Label comes from the raw logits; calibration only rescales confidence.
            let top = logits.indices.max(by: { logits[$0] < logits[$1] }) ?? 0
            return (calibratedProbs(from: logits, maps: maps), top)
        }
        if let model = coreMLModel, let probs = coreMLProbabilities(text, model: model) {
            return (probs, probs.indices.max(by: { probs[$0] < probs[$1] }) ?? 0)
        }
        let probs = softmax(tfidfLogits(text))
        return (probs, probs.indices.max(by: { probs[$0] < probs[$1] }) ?? 0)
    }

    /// Logits for calibration — CoreML's linear layer if the model exposes a
    /// "logits" output, otherwise the pure-Swift TF-IDF + LogReg computation.
    private func logitsForScoring(_ text: String) -> [Double] {
        if let model = coreMLModel, let logits = coreMLLogits(text, model: model) {
            return logits
        }
        // CM-3: log every time we miss CoreML logits so silent calibration degradation
        // is visible in Console.app (filter by subsystem com.stt.module, category IntentClassifier).
        logger.warning("coreMLLogits() returned nil — isotonic calibration falling back to Swift TF-IDF logits. Check that IntentClassifier.mlpackage exposes a 'logits' output.")
        return tfidfLogits(text)
    }

    /// Apply the per-class isotonic maps to logits and renormalise to a
    /// probability distribution. Falls back to softmax if the maps degenerate.
    private func calibratedProbs(from logits: [Double],
                                 maps: [(x: [Double], y: [Double])]) -> [Double] {
        guard logits.count == maps.count else { return softmax(logits) }
        let calibrated = logits.indices.map { interpolate(logits[$0], maps[$0].x, maps[$0].y) }
        let sum = calibrated.reduce(0, +)
        return sum > 0 ? calibrated.map { $0 / sum } : softmax(logits)
    }

    /// Clamped piecewise-linear interpolation over sorted breakpoints `xs`→`ys`.
    private func interpolate(_ x: Double, _ xs: [Double], _ ys: [Double]) -> Double {
        guard let first = xs.first, let firstY = ys.first else { return 0 }
        if x <= first { return firstY }
        if x >= xs[xs.count - 1] { return ys[ys.count - 1] }
        // xs is ascending; find the bracketing segment.
        var lo = 0, hi = xs.count - 1
        while hi - lo > 1 {
            let mid = (lo + hi) / 2
            if xs[mid] <= x { lo = mid } else { hi = mid }
        }
        let span = xs[hi] - xs[lo]
        guard span > 0 else { return ys[lo] }
        let t = (x - xs[lo]) / span
        return ys[lo] + t * (ys[hi] - ys[lo])
    }

    // MARK: - CoreML Stage 2

    /// Builds the CoreML input feature provider for `text`, or nil on failure.
    private func coreMLInput(for text: String) -> MLDictionaryFeatureProvider? {
        let vec = tfidfVector(for: text)   // [Double], length == idf.count
        let n   = vec.count
        // The exported model declares its "tfidf_vector" input as FLOAT64 (double).
        // A neuralNetwork model rejects a mismatched dtype, so build a .double array —
        // a .float32 array would make prediction throw and silently fall back to JSON.
        guard n > 0,
              let arr = try? MLMultiArray(shape: [n as NSNumber], dataType: .double)
        else { return nil }
        let arrPtr = arr.dataPointer.assumingMemoryBound(to: Double.self)
        for i in 0..<n { arrPtr[i] = vec[i] }
        return try? MLDictionaryFeatureProvider(dictionary: [
            "tfidf_vector": MLFeatureValue(multiArray: arr)
        ])
    }

    /// CoreML softmax probabilities aligned with `labels` (uncalibrated).
    private func coreMLProbabilities(_ text: String, model: MLModel) -> [Double]? {
        guard
            let input    = coreMLInput(for: text),
            let output   = try? model.prediction(from: input),
            // dictionaryValue returns [AnyHashable: Any] with NSNumber probability values.
            let probDict = output.featureValue(for: "classProbability")?.dictionaryValue
                           as? [String: NSNumber]
        else { return nil }
        // Re-align the dictionary into `labels` order so argmax stays consistent.
        return labels.map { probDict[$0]?.doubleValue ?? 0.0 }
    }

    /// CoreML raw logits aligned with `labels`, if the model exposes a "logits"
    /// output (added by export_coreml.py). Returns nil for older bundles, so the
    /// caller falls back to the pure-Swift logit computation.
    private func coreMLLogits(_ text: String, model: MLModel) -> [Double]? {
        guard
            let input  = coreMLInput(for: text),
            let output = try? model.prediction(from: input),
            let logits = output.featureValue(for: "logits")?.multiArrayValue,
            logits.count == labels.count
        else { return nil }
        return (0..<logits.count).map { logits[$0].doubleValue }
    }

    // MARK: - JSON weights TF-IDF (Stage 2 fallback)

    /// Loads coef + intercept on first call and caches them. Only triggered when CoreML
    /// prediction itself fails — never allocated when CoreML is healthy.
    /// Safe without locks — IntentClassifierService is an actor.
    @discardableResult
    private func ensureLogRegWeights() -> LogRegWeights? {
        if let w = logRegWeights { return w }
        guard
            let url  = weightsURL,
            let data = try? Data(contentsOf: url),
            let obj  = try? JSONSerialization.jsonObject(with: data) as? [String: Any]
        else {
            logger.error("LogReg fallback: failed to reload intent_classifier_weights.json")
            return nil
        }
        let w = LogRegWeights(
            coef:      obj["coef"]      as! [[Double]],
            intercept: obj["intercept"] as! [Double]
        )
        logger.warning("CoreML prediction failed — loaded LogReg weights into memory")
        logRegWeights = w
        return w
    }

    private func tfidfLogits(_ text: String) -> [Double] {
        guard let w = ensureLogRegWeights() else { return [Double](repeating: 0, count: labels.count) }
        let vec = tfidfVector(for: text)
        return w.coef.indices.map { c in
            zip(w.coef[c], vec).reduce(w.intercept[c]) { $0 + $1.0 * $1.1 }
        }
    }

    private func tfidfVector(for text: String) -> [Double] {
        let tokens = tokenize(text)
        var termCounts: [Int: Int] = [:]
        for token in tokens {
            if let idx = vocab[token] { termCounts[idx, default: 0] += 1 }
        }
        var vec = [Double](repeating: 0.0, count: idf.count)
        for (idx, count) in termCounts {
            vec[idx] = (1.0 + log(Double(count))) * idf[idx]  // sublinear TF
        }
        return l2Normalize(vec)
    }

    private func tokenize(_ text: String) -> [String] {
        let lower = text.lowercased()
        let words = lower.components(separatedBy: CharacterSet.alphanumerics.inverted)
                         .filter { !$0.isEmpty }
        var tokens = words
        for i in words.indices.dropLast() {
            tokens.append(words[i] + " " + words[i + 1])
        }
        return tokens
    }

    // MARK: - Math helpers

    private func softmax(_ logits: [Double]) -> [Double] {
        guard !logits.isEmpty else { return [] }
        let maxVal = logits.max()!
        let exps   = logits.map { exp($0 - maxVal) }
        let sum    = exps.reduce(0, +)
        return sum == 0 ? logits.map { _ in 1.0 / Double(logits.count) } : exps.map { $0 / sum }
    }

    private func l2Normalize(_ vec: [Double]) -> [Double] {
        let norm = sqrt(vec.reduce(0) { $0 + $1 * $1 })
        guard norm > 0 else { return vec }
        return vec.map { $0 / norm }
    }
}
