// SemanticEmbedder.swift
// STT
//
// Stage 3 embedding: BERT-style WordPiece tokeniser + CoreML MiniLM-L6-v2.
// Mirrors SemanticFallback._tokenise() / _embed_onnx() in
// IntentClassifier/scripts/nlu/semantic.py — same WordPiece tokeniser,
// same mean-pool over the attention mask, same L2 normalisation.
// Inputs are padded to a fixed 32-token length to match the re-exported
// (1, 32) fixed-shape MiniLM encoder, which keeps the model ANE-resident
// and sizes its memory exactly (see `maxLen` below). Embeddings are
// unchanged for any utterance of ≤ 32 tokens.
//
// Bundle requirements (both must be present for Stage 3 to activate):
//   MiniLMEmbedder.mlpackage  — generated by: python scripts/export_coreml.py
//   minilm-vocab.txt          — copy from IntentClassifier/models/minilm-vocab.txt
//
// If either file is missing, init() returns nil and the caller skips Stage 3.
// This is intentional: the app ships and functions at full TF-IDF + keyword
// accuracy; semantic rescue activates only when the CoreML model is bundled.

import CoreML
import Foundation

/// Embeds text into a 384-dimensional L2-normalised Float vector
/// using MiniLM-L6-v2 via CoreML (Apple Neural Engine on A12+).
// Immutable after init (model + vocab are `let`), so safe to hand across the
// background load Task in IntentClassifierService.
final class SemanticEmbedder: @unchecked Sendable {

    private let model: MLModel
    private let vocab: [String: Int]

    // Fixed CoreML input length. MUST equal the --seq-len the MiniLM model was
    // exported with (default 32). The encoder now has a fixed (1, 32) input
    // shape, so every prediction is padded to exactly this many tokens — a
    // mismatch makes model.prediction(...) fail. Utterances are ≤ 32 WordPiece
    // tokens in practice, so classification behaviour is unchanged.
    private static let maxLen = 32

    deinit {
        print("[Deinit] SemanticEmbedder (MLModel + vocab released)")
    }

    // MARK: - Init

    init?() {
        let miniLMURL = Bundle.main.url(forResource: "MiniLMEmbedder", withExtension: "mlmodelc")
                     ?? Bundle.main.url(forResource: "MiniLMEmbedder", withExtension: "mlpackage")
        guard
            let modelURL = miniLMURL,
            let vocabURL = Bundle.main.url(forResource: "minilm-vocab",
                                           withExtension: "txt"),
            let vocabText = try? String(contentsOf: vocabURL, encoding: .utf8)
        else { return nil }

        let config = MLModelConfiguration()
        // Pin to CPU + Neural Engine. `.all` lets CoreML split the graph across
        // CPU/GPU/ANE and can hold duplicate weight buffers; with the fixed
        // (1, 32) shape the encoder stays ANE-resident here. (Worth measuring
        // `.cpuOnly` too and keeping whichever shows lower RAM/latency on device.)
        config.computeUnits = .cpuAndNeuralEngine
        guard let m = try? MLModel(contentsOf: modelURL, configuration: config) else { return nil }
        model = m

        var v = [String: Int]()
        v.reserveCapacity(30_722)        // standard BERT vocab size
        for (i, line) in vocabText.components(separatedBy: "\n").enumerated() {
            let tok = line.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !tok.isEmpty else { continue }
            v[tok] = i
        }
        vocab = v
    }

    // MARK: - Public API

    /// Produces a 384-element L2-normalised embedding, or nil on any failure.
    /// Async so CoreML scheduling doesn't block the calling actor.
    func embed(_ text: String) async -> [Float]? {
        let (inputIDs, mask, tokenTypeIDs) = tokenize(text.lowercased())
        let n = inputIDs.count
        guard n > 0 else { return nil }

        // The model input shape is fixed at (1, maxLen). Allocate at the fixed
        // length, zero-fill, and write the real tokens into the first `count`
        // slots. Pads are id=0 ([PAD]), mask=0, token_type=0 — mask=0 makes
        // attention ignore them, so the real-token outputs are identical to the
        // un-padded case (and so are the pooled embeddings, see below).
        let L = Self.maxLen   // 32 — MUST equal the model's exported --seq-len
        guard
            let idsArray  = try? MLMultiArray(shape: [1, L as NSNumber], dataType: .int32),
            let maskArray = try? MLMultiArray(shape: [1, L as NSNumber], dataType: .int32),
            let typeArray = try? MLMultiArray(shape: [1, L as NSNumber], dataType: .int32)
        else { return nil }

        // Write straight into the backing buffers — the arrays are freshly
        // allocated and contiguous, so element stride is 1. Avoids ~3L NSNumber
        // boxing allocations per call.
        let idsPtr  = idsArray.dataPointer.assumingMemoryBound(to: Int32.self)
        let maskPtr = maskArray.dataPointer.assumingMemoryBound(to: Int32.self)
        let typePtr = typeArray.dataPointer.assumingMemoryBound(to: Int32.self)
        let count = min(n, L)
        for i in 0..<L {
            idsPtr[i]  = i < count ? inputIDs[i]     : 0   // pad id   = 0 ([PAD])
            maskPtr[i] = i < count ? mask[i]         : 0   // pad mask = 0 (ignored by attention)
            typePtr[i] = i < count ? tokenTypeIDs[i] : 0
        }

        guard let featureProvider = try? MLDictionaryFeatureProvider(dictionary: [
            "input_ids":      MLFeatureValue(multiArray: idsArray),
            "attention_mask": MLFeatureValue(multiArray: maskArray),
            "token_type_ids": MLFeatureValue(multiArray: typeArray),
        ]) else { return nil }

        guard let output = try? await model.prediction(from: featureProvider) else { return nil }

        // CoreML output name matches the ONNX graph: "last_hidden_state",
        // now a fixed [1, 32, 384]. Pool over the real tokens only (`count`),
        // so the padded rows are excluded — embeddings match the un-padded case.
        guard let hidden = output.featureValue(for: "last_hidden_state")?.multiArrayValue
        else { return nil }

        return meanPoolAndNormalize(hidden, seqLen: count, mask: mask)
    }

    // MARK: - Tokenisation (mirrors semantic.py _tokenise)

    private func tokenize(_ text: String) -> (ids: [Int32], mask: [Int32], types: [Int32]) {
        let unk = Int32(vocab["[UNK]"] ?? 100)
        let cls = Int32(vocab["[CLS]"] ?? 101)
        let sep = Int32(vocab["[SEP]"] ?? 102)

        var ids: [Int32] = [cls]
        let pieces = wordpiece(text)
        for p in pieces.prefix(Self.maxLen - 2) {
            ids.append(Int32(vocab[p] ?? Int(unk)))
        }
        ids.append(sep)

        let mask  = [Int32](repeating: 1, count: ids.count)
        let types = [Int32](repeating: 0, count: ids.count)
        return (ids, mask, types)
    }

    // MARK: - WordPiece (mirrors semantic.py _wordpiece exactly)

    private func wordpiece(_ text: String) -> [String] {
        // re.findall(r"\w+|[^\w\s]", text) — words then isolated punctuation
        let pattern = try! NSRegularExpression(pattern: #"\w+|[^\w\s]"#)
        let range   = NSRange(text.startIndex..., in: text)
        let words   = pattern.matches(in: text, range: range).map {
            String(text[Range($0.range, in: text)!])
        }

        var result = [String]()
        for word in words {
            let chars = Array(word)
            if chars.count > 100 { result.append("[UNK]"); continue }

            var subTokens = [String]()
            var start     = 0
            var isBad     = false

            while start < chars.count {
                var found: String?
                var end = chars.count
                while start < end {
                    var substr = String(chars[start..<end])
                    if start > 0 { substr = "##" + substr }
                    if vocab[substr] != nil { found = substr; break }
                    end -= 1
                }
                if let f = found {
                    subTokens.append(f)
                    start = end
                } else {
                    isBad = true; break
                }
            }
            result.append(contentsOf: isBad ? ["[UNK]"] : subTokens)
        }
        return result
    }

    // MARK: - Mean pool + L2 normalise (mirrors _embed_onnx)

    private func meanPoolAndNormalize(_ hidden: MLMultiArray,
                                      seqLen: Int,
                                      mask: [Int32]) -> [Float] {
        let dim = 384
        var pooled      = [Float](repeating: 0, count: dim)
        var totalWeight: Float = 0

        // The output is [1, seq, dim]. Read it through the raw backing buffer using
        // the model's declared strides instead of MLMultiArray subscripting, which
        // boxes every element into an NSNumber (~seq*dim allocations per call).
        let strides   = hidden.strides.map { $0.intValue }
        let rowStride = strides.count >= 3 ? strides[1] : dim
        let colStride = strides.count >= 3 ? strides[2] : 1

        func pool<T: BinaryFloatingPoint>(_ base: UnsafeMutablePointer<T>) {
            for pos in 0..<seqLen {
                let w = Float(mask[pos])
                guard w != 0 else { continue }
                totalWeight += w
                let row = pos * rowStride
                for d in 0..<dim {
                    pooled[d] += Float(base[row + d * colStride]) * w
                }
            }
        }

        func poolBySubscript() {
            for pos in 0..<seqLen {
                let w = Float(mask[pos])
                guard w != 0 else { continue }
                totalWeight += w
                for d in 0..<dim {
                    pooled[d] += hidden[[0, NSNumber(value: pos), NSNumber(value: d)]].floatValue * w
                }
            }
        }

        // NOTE: MLMultiArrayDataType.float16 is an iOS 16+ symbol, so it must be
        // referenced only inside an availability guard (not a bare switch case).
        // Pre-iOS16, CoreML hands back FP16 outputs as .float32 anyway.
        let dt = hidden.dataType
        if dt == .float32 {
            pool(hidden.dataPointer.assumingMemoryBound(to: Float.self))
        } else if dt == .double {
            pool(hidden.dataPointer.assumingMemoryBound(to: Double.self))
        } else if #available(iOS 16.0, *), dt == .float16 {
            pool(hidden.dataPointer.assumingMemoryBound(to: Float16.self))
        } else {
            poolBySubscript()
        }

        if totalWeight > 0 { for d in 0..<dim { pooled[d] /= totalWeight } }

        // L2 normalise — mandatory; the head was trained on normalised embeddings
        let norm = sqrt(pooled.reduce(0) { $0 + $1 * $1 })
        if norm > 0 { for d in 0..<dim { pooled[d] /= norm } }
        return pooled
    }
}
