// SemanticEmbedder.swift
// STT
//
// Stage 3 embedding: BERT-style WordPiece tokeniser + CoreML MiniLM-L6-v2.
// Mirrors SemanticFallback._tokenise() / _embed_onnx() in
// IntentClassifier/scripts/nlu/semantic.py exactly — same max_len=64,
// same mean-pool over attention mask, same L2 normalisation.
//
// Bundle requirements (both must be present for Stage 3 to activate):
//   MiniLMEmbedder.mlpackage  — generated by: python scripts/export_coreml.py
//   minilm-vocab.txt          — copy from IntentClassifier/models/minilm-vocab.txt
//
// If either file is missing, init() returns nil and the caller skips Stage 3.
// This is intentional: the app ships and functions at full TF-IDF + keyword
// accuracy; semantic rescue activates only when the CoreML model is bundled.

import CoreML
import Foundation

/// Embeds text into a 384-dimensional L2-normalised Float vector
/// using MiniLM-L6-v2 via CoreML (Apple Neural Engine on A12+).
final class SemanticEmbedder {

    private let model: MLModel
    private let vocab: [String: Int]

    // Matches Python's max_len=64 in _tokenise()
    private static let maxLen = 64

    // MARK: - Init

    init?() {
        guard
            let modelURL = Bundle.main.url(forResource: "MiniLMEmbedder",
                                           withExtension: "mlpackage"),
            let vocabURL = Bundle.main.url(forResource: "minilm-vocab",
                                           withExtension: "txt"),
            let vocabText = try? String(contentsOf: vocabURL, encoding: .utf8)
        else { return nil }

        let config = MLModelConfiguration()
        config.computeUnits = .all       // prefers ANE on A12+, GPU fallback on older
        guard let m = try? MLModel(contentsOf: modelURL, configuration: config) else { return nil }
        model = m

        var v = [String: Int]()
        v.reserveCapacity(30_722)        // standard BERT vocab size
        for (i, line) in vocabText.components(separatedBy: "\n").enumerated() {
            let tok = line.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !tok.isEmpty else { continue }
            v[tok] = i
        }
        vocab = v
    }

    // MARK: - Public API

    /// Produces a 384-element L2-normalised embedding, or nil on any failure.
    /// Async so CoreML scheduling doesn't block the calling actor.
    func embed(_ text: String) async -> [Float]? {
        let (inputIDs, mask, tokenTypeIDs) = tokenize(text.lowercased())
        let n = inputIDs.count

        guard n > 0,
              let idsArray  = try? MLMultiArray(shape: [1, n as NSNumber], dataType: .int32),
              let maskArray = try? MLMultiArray(shape: [1, n as NSNumber], dataType: .int32),
              let typeArray = try? MLMultiArray(shape: [1, n as NSNumber], dataType: .int32)
        else { return nil }

        for i in 0..<n {
            idsArray[[0, i] as [NSNumber]]  = NSNumber(value: inputIDs[i])
            maskArray[[0, i] as [NSNumber]] = NSNumber(value: mask[i])
            typeArray[[0, i] as [NSNumber]] = NSNumber(value: tokenTypeIDs[i])
        }

        guard let featureProvider = try? MLDictionaryFeatureProvider(dictionary: [
            "input_ids":      MLFeatureValue(multiArray: idsArray),
            "attention_mask": MLFeatureValue(multiArray: maskArray),
            "token_type_ids": MLFeatureValue(multiArray: typeArray),
        ]) else { return nil }

        guard let output = try? await model.prediction(from: featureProvider) else { return nil }

        // CoreML output name matches the ONNX graph: "last_hidden_state" shape [1, seqLen, 384]
        guard let hidden = output.featureValue(for: "last_hidden_state")?.multiArrayValue
        else { return nil }

        return meanPoolAndNormalize(hidden, seqLen: n, mask: mask)
    }

    // MARK: - Tokenisation (mirrors semantic.py _tokenise)

    private func tokenize(_ text: String) -> (ids: [Int32], mask: [Int32], types: [Int32]) {
        let unk = Int32(vocab["[UNK]"] ?? 100)
        let cls = Int32(vocab["[CLS]"] ?? 101)
        let sep = Int32(vocab["[SEP]"] ?? 102)

        var ids: [Int32] = [cls]
        let pieces = wordpiece(text)
        for p in pieces.prefix(Self.maxLen - 2) {
            ids.append(Int32(vocab[p] ?? Int(unk)))
        }
        ids.append(sep)

        let mask  = [Int32](repeating: 1, count: ids.count)
        let types = [Int32](repeating: 0, count: ids.count)
        return (ids, mask, types)
    }

    // MARK: - WordPiece (mirrors semantic.py _wordpiece exactly)

    private func wordpiece(_ text: String) -> [String] {
        // re.findall(r"\w+|[^\w\s]", text) — words then isolated punctuation
        let pattern = try! NSRegularExpression(pattern: #"\w+|[^\w\s]"#)
        let range   = NSRange(text.startIndex..., in: text)
        let words   = pattern.matches(in: text, range: range).map {
            String(text[Range($0.range, in: text)!])
        }

        var result = [String]()
        for word in words {
            let chars = Array(word)
            if chars.count > 100 { result.append("[UNK]"); continue }

            var subTokens = [String]()
            var start     = 0
            var isBad     = false

            while start < chars.count {
                var found: String?
                var end = chars.count
                while start < end {
                    var substr = String(chars[start..<end])
                    if start > 0 { substr = "##" + substr }
                    if vocab[substr] != nil { found = substr; break }
                    end -= 1
                }
                if let f = found {
                    subTokens.append(f)
                    start = end
                } else {
                    isBad = true; break
                }
            }
            result.append(contentsOf: isBad ? ["[UNK]"] : subTokens)
        }
        return result
    }

    // MARK: - Mean pool + L2 normalise (mirrors _embed_onnx)

    private func meanPoolAndNormalize(_ hidden: MLMultiArray,
                                      seqLen: Int,
                                      mask: [Int32]) -> [Float] {
        let dim = 384
        var pooled      = [Float](repeating: 0, count: dim)
        var totalWeight: Float = 0

        for pos in 0..<seqLen {
            let w = Float(mask[pos])
            totalWeight += w
            for d in 0..<dim {
                let idx: [NSNumber] = [0, NSNumber(value: pos), NSNumber(value: d)]
                pooled[d] += hidden[idx].floatValue * w
            }
        }
        if totalWeight > 0 { pooled = pooled.map { $0 / totalWeight } }

        // L2 normalise — mandatory; the head was trained on normalised embeddings
        let norm = sqrt(pooled.reduce(0) { $0 + $1 * $1 })
        if norm > 0 { pooled = pooled.map { $0 / norm } }
        return pooled
    }
}
