// PackDateTimeParityTests.swift
// VoiceAIKitTests
//
// Proves `PackDateTimeParser` resolves an utterance to the same instant as the
// Python engine that trained the model.
//
// WHY THIS FILE EXISTS
// The parser was written by reading `entities.py::extract_datetime` and
// mirroring its branch order. That process caught four divergences that would
// all have shipped silently:
//
//   * `_pick_future_hour` treats hours 1–6 as PM with no am/pm hint. Getting
//     that wrong put every ambiguous reminder twelve hours out.
//   * a colon time is NOT an explicit am/pm, so "9:30" at 10:00 is 21:30 today,
//     not 09:30 tomorrow.
//   * "tonight" is both a day anchor and a period name; consuming it as the
//     anchor left the period lookup empty and produced a 09:00 default.
//   * "in the morning" must stay non-explicit so it rolls to tomorrow.
//
// None of those raise, log or crash. They return a plausible datetime that is
// simply wrong, which is the failure mode a user reports as "the reminder went
// off at the wrong time" weeks later. Reading is not verification — this is.
//
// Expectations live in `Fixtures/reference_expectations.json`, generated by
// running the reference at a FIXED clock. Regenerate it whenever the reference
// changes; do not hand-edit.

import XCTest
@testable import VoiceAIKit

final class PackDateTimeParityTests: XCTestCase {

    private var parser: PackDateTimeParser!
    private var reference: PackTestSupport.Reference!
    private var now: Date!

    override func setUpWithError() throws {
        try super.setUpWithError()
        let pack = try PackTestSupport.loadPack()
        // UTC because the fixtures are UTC. A local time zone would make the
        // suite pass or fail depending on where it runs.
        parser = PackDateTimeParser(grammar: pack.lexicon.datetime,
                                    timeZone: TimeZone(identifier: "UTC")!)
        reference = try PackTestSupport.reference()
        now = try PackTestSupport.referenceNow(reference)
    }

    // MARK: - The whole corpus

    /// Cases the pack cannot currently express, with the reason.
    ///
    /// These are CONTRACT gaps, not parser bugs, and they are listed rather than
    /// deleted so the divergence stays visible. Remove an entry the moment the
    /// pack can carry it — a permanently red suite gets ignored, and a silently
    /// shortened fixture set is worse.
    ///
    /// `numbers_0_to_31` is named for dates and stops at 31, so no pack carries
    /// "forty" or "fifty". The reference resolves "four fifty" to 16:50 through
    /// a hardcoded `_WORD_NUMS` table that includes 40/50/60 precisely for clock
    /// minutes. See VIK-014.
    private static let knownContractGaps: Set<String> = ["four fifty"]

    func testEveryReferenceCaseResolvesIdentically() throws {
        var failures: [String] = []

        for expected in reference.datetime {
            if Self.knownContractGaps.contains(expected.text) { continue }
            let actual = parser.parse(expected.text, now: now)

            guard let expectedISO = expected.iso else {
                if let actual {
                    failures.append("""
                        \(expected.text.debugDescription): reference resolved NOTHING, \
                        parser returned \(actual.date)
                        """)
                }
                continue
            }
            guard let actual else {
                failures.append("\(expected.text.debugDescription): expected \(expectedISO), got nil")
                continue
            }
            guard let expectedDate = PackTestSupport.instant(expectedISO) else {
                failures.append("\(expected.text.debugDescription): unparsable fixture \(expectedISO)")
                continue
            }
            if actual.date != expectedDate {
                failures.append("""
                    \(expected.text.debugDescription): expected \(expectedDate), got \(actual.date)
                    """)
            }
            if actual.timeExplicit != expected.timeExplicit {
                failures.append("""
                    \(expected.text.debugDescription): timeExplicit expected \
                    \(expected.timeExplicit), got \(actual.timeExplicit)
                    """)
            }
            if actual.dayExplicit != expected.dayExplicit {
                failures.append("""
                    \(expected.text.debugDescription): dayExplicit expected \
                    \(expected.dayExplicit), got \(actual.dayExplicit)
                    """)
            }
        }

        XCTAssertTrue(failures.isEmpty, """
            \(failures.count) divergence(s) from the Python reference:
            \(failures.joined(separator: "\n"))
            """)
    }

    // MARK: - The four bugs, named
    //
    // Covered by the corpus test above, but called out individually so a
    // regression names the rule it broke instead of appearing as one of N
    // failures in a list.

    /// A bare hour takes the EARLIEST reading still ahead of the clock.
    ///
    /// This replaced `1-6 -> PM, 7-12 -> AM`, which guessed the half of the clock
    /// before consulting `now` and only looked at the time to rescue a guess that
    /// had landed in the past. "wake me at 6" said at 05:41 scheduled 18:00, with
    /// 06:00 nineteen minutes away and in the future. The old rule was also an
    /// English-speaking assumption compiled into the engine that no language pack
    /// could disagree with, and narrowing its range would only have retuned the
    /// magic number. There is no constant now: the answer comes from the clock.
    ///
    /// Both branches are asserted, because the rule is only legible as a pair:
    ///
    ///   * a NAMED DAY — both readings are ahead, so the earliest wins and
    ///     "saturday at 6" is 06:00. This is the accepted cost of the rule,
    ///     documented at the implementation: saying "6 pm" is the user's half of
    ///     the contract.
    ///   * TODAY with the morning reading already past — "at 5" at 10:00 can only
    ///     mean 17:00.
    ///
    /// The corpus test above covers both from the reference fixture; they are
    /// named here so a regression says which half of the rule it broke.
    func testBareHourTakesTheEarliestReadingStillAhead() throws {
        let namedDay = try XCTUnwrap(parser.parse("saturday at 6", now: now))
        XCTAssertEqual(namedDay.date, PackTestSupport.instant("2026-08-08T06:00:00Z"),
                       "on a named day both readings are ahead, so 6 is 06:00 — "
                       + "18:00 would be the old 1-6-means-PM guess")

        let today = try XCTUnwrap(parser.parse("at 5", now: now))
        XCTAssertEqual(today.date, PackTestSupport.instant("2026-08-03T17:00:00Z"),
                       "05:00 is already past at 10:00, so 5 can only mean 17:00")
    }

    /// A colon supplies minutes, not a half of the clock.
    func testColonTimeIsNotTreatedAsExplicitAMPM() throws {
        let match = try XCTUnwrap(parser.parse("9:30", now: now))
        XCTAssertEqual(match.date, PackTestSupport.instant("2026-08-03T21:30:00Z"),
                       "09:30 is already past at 10:00, so 9:30 means tonight — not tomorrow morning")
    }

    /// "tonight" is a day anchor AND a period name.
    func testTonightCarriesBothDayAndTime() throws {
        let match = try XCTUnwrap(parser.parse("tonight", now: now))
        XCTAssertEqual(match.date, PackTestSupport.instant("2026-08-03T18:00:00Z"))
        XCTAssertTrue(match.timeExplicit, "tonight names a time; it must not fall back to 09:00")
        XCTAssertTrue(match.dayExplicit, "tonight also names a day")
    }

    /// A period hint keeps driving disambiguation.
    func testNamedPeriodRollsForwardWhenAlreadyPast() throws {
        let match = try XCTUnwrap(parser.parse("in the morning", now: now))
        XCTAssertEqual(match.date, PackTestSupport.instant("2026-08-04T08:00:00Z"),
                       "08:00 has passed at 10:00, so the morning means tomorrow")
    }

    // MARK: - Guards

    /// A past day is a no-match, never a date in the past.
    func testPastDayIsRejected() {
        XCTAssertNil(parser.parse("yesterday", now: now))
    }

    /// The ordinal-context gate. Without it "wait a second" becomes "wait a 2nd"
    /// and the clock parser claims the 2.
    func testBareOrdinalWithoutDateContextIsNotADate() {
        XCTAssertNil(parser.parse("wait a second", now: now),
                     "a bare ordinal must not fabricate a datetime")
    }

    func testTextWithNoTemporalSignalResolvesNothing() {
        XCTAssertNil(parser.parse("hello there", now: now))
        XCTAssertNil(parser.parse("", now: now))
    }

    /// VIK-014, asserted rather than described so it cannot be forgotten.
    ///
    /// Spoken clock minutes above 31 have no vocabulary in the pack:
    /// `numbers_0_to_31` is sized for days of the month. The reference resolves
    /// "four fifty" to 16:50 via a hardcoded table. When the pack gains those
    /// words this test flips to a failure — that is the signal to delete it and
    /// remove the entry from `knownContractGaps`.
    func testSpokenClockMinutesAboveThirtyOneAreAKnownGap() throws {
        XCTAssertNil(parser.parse("four fifty", now: now), """
            "four fifty" now resolves — the pack must have gained clock-minute \
            vocabulary. Remove this test and the knownContractGaps entry.
            """)
    }

    /// An impossible date must fail rather than silently resolve against
    /// another month.
    func testImpossibleDateInANamedMonthIsRejected() {
        XCTAssertNil(parser.parse("the thirty first of february", now: now),
                     "February has no 31st — honour the named month or fail")
    }

    // MARK: - Language neutrality

    /// Every table the parser uses comes from the pack, so an empty grammar must
    /// yield a parser that resolves nothing rather than falling back to English.
    func testEmptyGrammarResolvesNothingRatherThanDefaultingToEnglish() throws {
        let empty = try JSONDecoder().decode(DateTimeGrammar.self, from: Data("""
        {"day_anchors":{},"time_of_day":{},"weekdays":{},"months":{},
         "numbers_0_to_31":{},"ordinals_1_to_31":{},
         "relative_markers":{},"relative_units":{}}
        """.utf8))
        let bare = PackDateTimeParser(grammar: empty, timeZone: TimeZone(identifier: "UTC")!)
        XCTAssertNil(bare.parse("tomorrow", now: now),
                     "with no grammar there is no vocabulary — English must not leak in")
    }
}
