// SlotTaggerParityTests.swift
// VoiceAIKitTests
//
// `PackSlotTagger` against the Python reference, row for row.
//
// Fixtures/slot_tagger_parity_en.json is GENERATED by the compiler repo's
// `scripts/ci/emit_slot_tagger_fixtures.py` from `JsonSlotTagger` — the Python
// scorer of the same weights file this type scores. It is copied here verbatim
// (from `tests/parity/slot_tagger/slot_tagger_en.json`) together with the
// weights it was generated from (Fixtures/slot_tagger_weights_en.json, from
// `language_packs/en/models/slot/slot_tagger_weights.json`), so this test proves
// the ALGORITHM independently of which pack the package currently seeds.
//
// Never hand-edit either file. Regenerating the fixture to turn a red row green
// destroys the only guard there is: re-copy BOTH files only when the model or the
// feature_spec changed on purpose.
//
// A failure names the stage that broke, which localises it:
//   TOKENS  -> regex dialect (preprocess or tokenizer)
//   TAGS    -> a feature built differently, or rel_pos rounding
//   TITLE   -> BIO decoding

import XCTest
@testable import VoiceAIKit

final class SlotTaggerParityTests: XCTestCase {

    private struct Fixture: Decodable {
        struct GeneratedFrom: Decodable {
            let featureSpecVersion: Int
            let classes: [String]
            let intercept: [Double]
            enum CodingKeys: String, CodingKey {
                case classes, intercept
                case featureSpecVersion = "feature_spec_version"
            }
        }
        struct Case: Decodable {
            let text: String
            let tokens: [String]
            let tags: [String]
            let title: String?
            let minMargin: Double?
            enum CodingKeys: String, CodingKey {
                case text, tokens, tags, title
                case minMargin = "min_margin"
            }
        }
        let generatedFrom: GeneratedFrom
        let cases: [Case]
        enum CodingKeys: String, CodingKey {
            case cases
            case generatedFrom = "generated_from"
        }
    }

    private static func fixtureURL(_ name: String) -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/\(name)")
    }

    private var weightsData: Data!
    private var tagger: PackSlotTagger!
    private var fixture: Fixture!

    override func setUpWithError() throws {
        try super.setUpWithError()
        weightsData = try Data(contentsOf: Self.fixtureURL("slot_tagger_weights_en.json"))
        tagger = try PackSlotTagger(weightsJSON: weightsData)
        fixture = try JSONDecoder().decode(
            Fixture.self,
            from: Data(contentsOf: Self.fixtureURL("slot_tagger_parity_en.json")))
    }

    /// The fixture and the weights beside it must be the same model, or every
    /// row below is compared against the wrong oracle.
    func testTheFixtureWasGeneratedFromTheseWeights() throws {
        let root = try XCTUnwrap(JSONSerialization.jsonObject(with: weightsData) as? [String: Any])
        let intercept = try XCTUnwrap(root["intercept"] as? [Double])
        XCTAssertEqual(intercept, fixture.generatedFrom.intercept,
                       "fixture and weights come from different training runs — re-copy both")
        XCTAssertEqual(tagger.classes, fixture.generatedFrom.classes)
        XCTAssertEqual(tagger.featureSpecVersion, fixture.generatedFrom.featureSpecVersion)
    }

    func testEveryRowMatchesThePythonReference() throws {
        XCTAssertGreaterThanOrEqual(fixture.cases.count, 250, "fixture looks truncated")

        var failures: [String] = []
        var smallestPassingMargin = Double.infinity

        for (index, row) in fixture.cases.enumerated() {
            let tokens = tagger.prepare(row.text)
            if tokens != row.tokens {
                failures.append("#\(index) TOKENS '\(row.text)'\n    swift  \(tokens)\n    python \(row.tokens)")
                continue
            }
            let tags = tagger.tag(tokens)
            if tags != row.tags {
                failures.append("#\(index) TAGS '\(row.text)'\n    swift  \(tags)\n    python \(row.tags)")
                continue
            }
            let title = tagger.title(of: row.text)
            if title != row.title {
                failures.append("#\(index) TITLE '\(row.text)' swift=\(title ?? "nil") python=\(row.title ?? "nil")")
                continue
            }
            if let margin = tagger.margins(tokens).min() {
                smallestPassingMargin = min(smallestPassingMargin, margin)
            }
        }

        XCTAssertTrue(failures.isEmpty, """
            \(failures.count)/\(fixture.cases.count) rows disagree with the Python reference:
            \(failures.prefix(10).joined(separator: "\n"))
            """)
        // Printed, not asserted: if this is comfortably above zero and rows still
        // fail, the failure is logic, not floating point.
        print("[SlotTaggerParity] \(fixture.cases.count - failures.count)/\(fixture.cases.count) rows match, "
              + "smallest passing margin \(smallestPassingMargin)")
    }

    // MARK: - The portability primitives

    /// Python's `round(i / n, 1)` is half-to-even on the exact binary value.
    /// Values chosen where `.rounded()` would disagree.
    func testRelPosRoundsLikePython() {
        XCTAssertEqual(roundLikePython(0.25, 1), 0.2)    // exact tie -> even
        XCTAssertEqual(roundLikePython(0.75, 1), 0.8)    // exact tie -> even
        XCTAssertEqual(roundLikePython(0.35, 1), 0.3)    // 0.34999… -> down
        XCTAssertEqual(roundLikePython(0.05, 1), 0.1)    // 0.05000…0277 -> up
        XCTAssertEqual(roundLikePython(0.0, 1), 0.0)
        XCTAssertEqual(roundLikePython(0.96, 1), 1.0)    // carries into the units
    }

    /// Python counts code points; Swift's `count` counts grapheme clusters.
    func testAffixesCountCodePointsNotGraphemes() {
        let decomposed = "cafe\u{0301}"                  // "café" as e + combining acute
        XCTAssertEqual(decomposed.count, 4)
        XCTAssertEqual(PackSlotTagger.scalarSuffix(decomposed, 2), "e\u{0301}")
        XCTAssertEqual(PackSlotTagger.scalarPrefix(decomposed, 5), decomposed)
    }

    func testIsDigitMatchesPython() {
        XCTAssertTrue(PackSlotTagger.isPythonDigit("42"))
        XCTAssertTrue(PackSlotTagger.isPythonDigit("\u{0663}"))   // Arabic-Indic three: Decimal
        XCTAssertTrue(PackSlotTagger.isPythonDigit("\u{00B2}"))   // superscript two: Digit
        XCTAssertFalse(PackSlotTagger.isPythonDigit("\u{00BD}"))  // one half: Numeric only
        XCTAssertFalse(PackSlotTagger.isPythonDigit(""))
        XCTAssertFalse(PackSlotTagger.isPythonDigit("4pm"))
    }

    // MARK: - Refusing a bad file

    private func mutatedWeights(_ change: (inout [String: Any]) -> Void) throws -> Data {
        var root = try XCTUnwrap(JSONSerialization.jsonObject(with: weightsData) as? [String: Any])
        change(&root)
        return try JSONSerialization.data(withJSONObject: root)
    }

    func testAWeightsRowOfTheWrongLengthIsRefused() throws {
        let data = try mutatedWeights { root in
            var weights = root["weights"] as? [String: Any] ?? [:]
            weights["bias"] = [0.1, 0.2]
            root["weights"] = weights
        }
        XCTAssertThrowsError(try PackSlotTagger(weightsJSON: data)) { error in
            guard case PackSlotTagger.LoadError.malformed = error else {
                return XCTFail("expected .malformed, got \(error)")
            }
        }
    }

    func testAMissingSpecKeyIsRefusedNotDefaulted() throws {
        let data = try mutatedWeights { root in
            var spec = root["feature_spec"] as? [String: Any] ?? [:]
            spec.removeValue(forKey: "trigger_window")
            root["feature_spec"] = spec
        }
        XCTAssertThrowsError(try PackSlotTagger(weightsJSON: data)) { error in
            guard case PackSlotTagger.LoadError.malformed = error else {
                return XCTFail("expected .malformed, got \(error)")
            }
        }
    }

    func testAnUnsupportedFeatureSpecIsReportedAsSuch() throws {
        let data = try mutatedWeights { root in
            var spec = root["feature_spec"] as? [String: Any] ?? [:]
            spec["version"] = 3
            root["feature_spec"] = spec
        }
        XCTAssertThrowsError(try PackSlotTagger(weightsJSON: data)) { error in
            XCTAssertEqual(error as? PackSlotTagger.LoadError,
                           .unsupportedFeatureSpec(found: 3, supported: 2))
        }
    }

    // MARK: - Manifest

    /// `device_weights_artifact` decodes and is part of the existence check, so a
    /// pack that names weights it does not ship is refused at load.
    func testTheManifestDeclaresTheDeviceWeights() throws {
        let json = """
            {"slot_tagger": {"en": {
                "artifact": "models/slot/en/slot_tagger_weights.json",
                "format": "json",
                "model_version": "en-1.0.62",
                "device_weights_artifact": "models/slot/en/slot_tagger_weights.json"}}}
            """
        let catalog = try JSONDecoder().decode(NLUBundle.ModelCatalog.self, from: Data(json.utf8))
        let spec = try XCTUnwrap(catalog.spec(family: "slot_tagger", scope: "en"))
        XCTAssertEqual(spec.deviceWeightsArtifact, "models/slot/en/slot_tagger_weights.json")
        XCTAssertTrue(spec.declaredPaths.contains("models/slot/en/slot_tagger_weights.json"))
    }

    /// When the seeded pack ships a tagger, it must be the model the fixture
    /// describes. Skipped until the seed pack carries one (v1.0.61 does not).
    func testTheSeededPackTaggerIsTheFixtureModel() throws {
        let pack = try PackTestSupport.loadPack()
        guard let seeded = pack.slotTagger else {
            throw XCTSkip("seed pack \(pack.manifest.bundleID) ships no slot tagger")
        }
        XCTAssertEqual(seeded.classes, fixture.generatedFrom.classes)
        for row in fixture.cases {
            XCTAssertEqual(seeded.title(of: row.text), row.title, "'\(row.text)'")
        }
    }
}
